namespace Clipthrough.Models;

public enum TextTransformation
{
    None,
    UpperCase,
    LowerCase,
    TitleCase,
    SentenceCase,
    UpperCamelCase,
    LowerCamelCase,
    FromCamelCase,
    TrimWhitespace,
    CollapseWhitespace,
    TabsToSpaces,
    SpacesToTabs,
    NormalizeEol,
    LinesToJsonArray,
    JoinWithDelimiter,
    SortLines,
    ReverseLines,
    RemoveEmptyLines,
    RemoveDuplicateLines,
    BoxTableToHtml,
    JsonQuote,
    JsonUnquote,
    JsonMinify,
    JsonPretty,
    UrlEncode,
    UrlDecode,
    Base64Encode,
    Base64Decode,
    CleanTerminalFormatting,
    HtmlToMarkdown,
    MarkdownToHtml,
}
