<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
        <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
        <Nullable>enable</Nullable>
        <Version>0.1.0</Version>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <RootNamespace>Clipthrough</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" Exclude="Assets\SemanticModel\**" />
        <Content Include="Assets\SemanticModel\**" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.1" />
        <PackageReference Include="Avalonia.AvaloniaEdit" Version="12.0.0" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.0.0" />
        <PackageReference Include="Avalonia.Desktop" Version="12.0.1" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.1" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.1" />
        <PackageReference Include="AvaloniaEdit.TextMate" Version="12.0.0" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="5.3.0" />
        <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.0" />
        <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.24.4" />
        <PackageReference Include="Microsoft.ML.Tokenizers" Version="1.0.2" />
        <PackageReference Include="ReactiveUI.Avalonia" Version="11.4.12" />
        <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.0" />
        <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.1.10" />
        <PackageReference Include="Avalonia.HtmlRenderer" Version="12.0.0" />
        <PackageReference Include="RtfPipe" Version="2.0.7677.4303" />
        <PackageReference Include="System.Drawing.Common" Version="10.0.0" />
        <PackageReference Include="Tmds.DBus.Protocol" Version="0.92.0" />
        <PackageReference Include="Velopack" Version="0.0.1298" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\external\ShareX.ImageEditor\ShareX.ImageEditor.csproj" />
    </ItemGroup>
</Project>
