<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <RootNamespace>AvaloniaApplication1</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.12" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.1.1" />
        <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
        <PackageReference Include="ReactiveUI.Avalonia" Version="11.3.8" />
    </ItemGroup>
</Project>
